[package]
name = "rusty-json"
version = "0.1.0"
authors = ["ray <chenjunhong2@xiaojiaoyu100.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.13"